stages:
  split:
    cmd: python src/data/1-train_test_split.py
    deps:
    - data/raw_data/raw.csv
    - src/data/1-train_test_split.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize:
    cmd: python src/data/2-normalisation.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/data/2-normalisation.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
  gridsearch:
    cmd: python src/models/3-gridsearch.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
    - src/models/3-gridsearch.py
    outs:
    - models/best_params.pkl
  training:
    cmd: python src/models/4-train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/models/4-train_model.py
    outs:
    - models/trained_model.pkl
